# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppt_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide_template',
            old_name='filename',
            new_name='template_name',
        ),
        migrations.AlterField(
            model_name='slide_template',
            name='template',
            field=models.FileField(blank=True, default=0, upload_to=b''),
        ),
    ]
